Creating a ModalFooterConfirm component
gathercontent/gather-ui pull request #934
Opened 2021-02-01 11:36 UTC by DavidHollins6

### 💬 Description
A component for the ModalFooterConfirm modal! It's just a nice footer with some buttons and some text.

### 🔗 Links
https://www.figma.com/file/66iSurBAx32DWrJymo9NKL/GCDS-%E2%80%93-Web-UI?node-id=6266%3A832
### 📹 GIF (optional)
https://share.getcloudapp.com/NQuJzXBb

### ✅ Checklist
- [ ] Tests written
- [ ] Browser tested
- [ ] Added to documentation
- [ ] Added to storybook

2021-02-01 11:37 UTC, DavidHollins6 commented
![](https://github.trello.services/images/mini-trello-icon.png) [ModalFooterConfirm Component](https://trello.com/c/PZntc0g4/1019-modalfooterconfirm-component)

2021-02-02 09:51 UTC, altaudio requested changes
This might be a wider question, but I was expecting the component to contain the primary and secondary buttons - not for them to be passed into the component at the app level.

To me a confirm footer has two buttons - "Confirm" and "Cancel" (not strictly that wording, but functionally).

If I can put any buttons in, what makes this a confirm footer?

I feel like we should be stricter on what these can do so we don't end up modifying these and losing the advantage of standardisation.

2021-02-02 10:16 UTC, DavidHollins6 commented
> This might be a wider question, but I was expecting the component to contain the primary and secondary buttons - not for them to be passed into the component at the app level.
> 
> To me a confirm footer has two buttons - "Confirm" and "Cancel" (not strictly that wording, but functionally).
> 
> If I can put any buttons in, what makes this a confirm footer?
> 
> I feel like we should be stricter on what these can do so we don't end up modifying these and losing the advantage of standardization.
> 
> That said, everything else on here is looking really good so far 🚀

I agree with this. I think I over-engineered this yesterday, the buttons should definitely be in the component.

2021-02-02 10:42 UTC, kyleharper approved these changes

2021-02-02 15:49 UTC, merged